project_id = "movevcbcaohumwrtxrsu"

[functions.daily-key]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.admin-validate]
verify_jwt = false

[functions.admin-logout]
verify_jwt = false

[functions.admin-stats]
verify_jwt = false