// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://movevcbcaohumwrtxrsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vdmV2Y2JjYW9odW13cnR4cnN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MTA4MDIsImV4cCI6MjA3MDA4NjgwMn0.3OS5mWlkwz_NCk7rm71Asv_8KX4x2fkyiMYGW1Q2EiE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});